addons:
  postgresql: "9.6"
  apt:
    packages:
      - curl
      - wget
      - ca-certificates
      - build-essential
      - postgresql-9.6
      - postgresql-contrib-9.6
      - postgresql-server-dev-9.6

language: c

cache: cargo

services:
  - postgresql

before_install: curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh

install: make && sudo make install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./setup_regress presto && make installcheck; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./setup_regress hive && make installcheck; fi'
